#!/bin/sh
#
# chkconfig: 2345 93 25
# description: Starts JBoss Operations Network (JON) server at system startup
#
# processname: java

. /etc/profile.d/jon-server.sh
script="${RHQ_SERVER_HOME}/bin/rhqctl"

start() {
    su -m ${RHQ_SERVER_USER} -c "${script} start"
}

stop() {
    su -m ${RHQ_SERVER_USER} -c "${script} stop"
}

restart() {
    su -m ${RHQ_SERVER_USER} -c "${script} restart"
}

status() {
    su -m ${RHQ_SERVER_USER} -c "${script} status"
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    status)
        $1
        ;;
    *)
        echo $"Usage: $0
{start|stop|status|restart}"
        exit 2
esac
exit $?
